name: py50-streamlit

channels:
  - conda-forge

dependencies:
  - streamlit==1.34.0
  - streamlit-extras
  - streamlit_ketcher
  - streamlit-activities-menu
  - pandas
  - numpy
  - matplotlib>=3.8.1
  - lxml
  - seaborn>=0.12
  - py50==1.0.6

