name: py50-streamlit

channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - pip
  - pip:
    - streamlit==1.36.0
    - streamlit-extras
    - streamlit_ketcher
    - streamlit-activities-menu
    - lxml
    - py50==1.0.9
